plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.github.node-gradle.node" version "7.0.2"
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

node {
    version = '18.17.1'
    npmVersion = '9.6.7'
    download = true
    workDir = file("${project.buildDir}/node")
    npmWorkDir = file("${project.buildDir}/npm")
    nodeProjectDir = file('frontend')
}

tasks.named('npmRunBuild', com.github.gradle.node.npm.task.NpmTask) {
    args += ['--loglevel', 'verbose']
}

repositories {
    mavenCentral()
}


dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // implementation 'org.springframework.boot:spring-boot-starter-security'


    implementation 'org.springframework.boot:spring-boot-starter-web'
    // implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // SQLite
    implementation 'com.h2database:h2'

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// This task builds the frontend and copies it into the Spring Boot resources directory
task copyFrontend(type: Copy) {
    dependsOn 'npm_run_build'
    from 'frontend/build'
    into 'build/resources/main/static'
}

// Make the 'processResources' task depend on our new 'copyFrontend' task
tasks.named('processResources') {
    dependsOn 'copyFrontend'
}

// The bootJar task will now automatically include the frontend files from the resources.
bootJar {
}
